// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)



/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  nodeSidebar: [
    {
      type: 'category',
      label: '介绍',
      items: [{ type: 'autogenerated', dirName: 'intro' }],
    },
    {
      type: 'category',
      label: '全栈学习',
      items: [{ type: 'autogenerated', dirName: 'docusaurus' }],
    },
    {
      type: 'category',
      label: '桌面端学习',
      items: [{ type: 'autogenerated', dirName: 'java' }],
    },
    {
      type: 'category',
      label: 'AI学习',
      items: [{ type: 'autogenerated', dirName: 'react' }],
    },
  ],

};

module.exports = sidebars;
